version: '3.3'

services:
  frontend:
    build: frontend
    image: felix/stremlit-app
    ports:
      - 80:${STREAMLIT_SERVER_PORT:-80}
    environment:
      - APP_BACKEND_URL=http://backend
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}
    depends_on:
      - backend

  backend:
    build: backend
    image: felix/fastapi-app
    ports:
      - 8080:80